/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    ReplaySummary: typeof import('./src/components/ReplaySummary.vue')['default']
    ReplayUpload: typeof import('./src/components/ReplayUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Th06Summary: typeof import('./src/components/tables/Th06Summary.vue')['default']
    Th08Summary: typeof import('./src/components/tables/Th08Summary.vue')['default']
    Th10Summary: typeof import('./src/components/tables/Th10Summary.vue')['default']
    Th11Summary: typeof import('./src/components/tables/Th11Summary.vue')['default']
    Th12Summary: typeof import('./src/components/tables/Th12Summary.vue')['default']
    Th13Summary: typeof import('./src/components/tables/Th13Summary.vue')['default']
    Th14Summary: typeof import('./src/components/tables/Th14Summary.vue')['default']
    Th15Summary: typeof import('./src/components/tables/Th15Summary.vue')['default']
    Th16Summary: typeof import('./src/components/tables/Th16Summary.vue')['default']
    Th17Summary: typeof import('./src/components/tables/Th17Summary.vue')['default']
    Th18Summary: typeof import('./src/components/tables/Th18Summary.vue')['default']
  }
}
